import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./Landing.module.css";
import { Modal, Typography, Button, Space } from "antd";
import { LockOutlined } from "@ant-design/icons";

const { Title, Paragraph } = Typography;

export default function Landing() {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState("");
  const [scrolled, setScrolled] = useState(false);
  const [isAuthModalVisible, setIsAuthModalVisible] = useState(false);

  // Handle scroll detection for the floating header
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 50) {
        setScrolled(true);
      } else {
        setScrolled(false);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const promptAuth = () => {
    setIsAuthModalVisible(true);
  };

  const onSearch = () => {
    promptAuth();
  };

  const scrollToSection = (id) => {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <div className={styles.pageWrapper}>
      {/* 1. FLOATING HEADER */}
      <header className={`${styles.header} ${scrolled ? styles.scrolled : ""}`}>
        <div className={styles.headerInner}>
          <div className={styles.brandGroup} onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
            <div className={styles.logoOrb}>💼</div>
            <span className={styles.brandTitle}>WorkStudy</span>
          </div>

          <nav className={styles.navLinks}>
            <span className={styles.navLink} onClick={() => scrollToSection('features')}>Platform</span>
            <span className={styles.navLink} onClick={() => scrollToSection('departments')}>Departments</span>
            <span className={styles.navLink} onClick={promptAuth}>Jobs</span>
          </nav>

          <div className={styles.authGroup}>
            <button className={styles.loginBtn} onClick={() => navigate('/login')}>Sign In</button>
            <button className={styles.registerBtn} onClick={() => navigate('/register')}>Get Started</button>
          </div>
        </div>
      </header>

      {/* 2. MAJESTIC HERO SECTION */}
      <section className={styles.heroSection}>
        <div className={styles.heroContent}>
          <div className={styles.heroBadge}>🔥 The #1 Student Work Platform</div>
          <h1 className={styles.heroTitle}>
            Find your dream <span className={styles.titleGradient}>work-study</span> role today.
          </h1>
          <p className={styles.heroSubtitle}>
            Connect instantly with top campus departments, log your hours seamlessly, and track your student employment all in one gorgeous platform.
          </p>

          <div className={styles.heroSearchBox}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ff3366" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{marginLeft: '16px'}}>
              <circle cx="11" cy="11" r="8"></circle>
              <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            </svg>
            <input 
              type="text" 
              className={styles.searchInput} 
              placeholder="Search IT jobs, Library, Admin..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') onSearch(); }}
            />
            <button className={styles.searchHeroBtn} onClick={onSearch}>Search</button>
          </div>
        </div>

        {/* Floating 3D Dashboard Image (Generated by Antigravity) */}
        <div className={styles.heroImageWrap}>
          <img src="/hero_dashboard.png" alt="Dashboard Preview" className={styles.heroDashboardImg} />
        </div>
      </section>

      {/* 3. INFINITE MARQUEE */}
      <section id="departments" className={styles.marqueeSection}>
        <div className={styles.marqueeTrack}>
          {/* Double up items to create seamless loop */}
          {[1, 2].map((group) => (
            <React.Fragment key={group}>
              <div className={styles.marqueeItem}><span>💻</span> INFORMATION TECHNOLOGY</div>
              <div className={styles.marqueeItem}><span>📚</span> CAMPUS LIBRARY</div>
              <div className={styles.marqueeItem}><span>🏢</span> ADMISSIONS OFFICE</div>
              <div className={styles.marqueeItem}><span>🔬</span> RESEARCH DEPT</div>
              <div className={styles.marqueeItem}><span>⚽</span> ATHLETICS</div>
              <div className={styles.marqueeItem}><span>🎨</span> DESIGN STUDIO</div>
              <div className={styles.marqueeItem}><span>🏥</span> HEALTH CENTER</div>
            </React.Fragment>
          ))}
        </div>
      </section>

      {/* 4. SPLIT FEATURE CARDS */}
      <section id="features" className={styles.featureSection}>
        <div className={styles.sectionHeader}>
          <h2>One platform. Two distinct experiences.</h2>
          <p>Built specifically to connect student ambition with administrative needs.</p>
        </div>

        <div className={styles.featureGrid}>
          {/* For Students Card */}
          <div className={`${styles.featureCard} ${styles.studentCard}`} onClick={promptAuth}>
            <div className={styles.cardIcon}>🎓</div>
            <h3>For Students</h3>
            <p>Discover roles tailored to your major, apply with one click, and easily submit your timesheets from any device. Your college career starts here.</p>
            <span className={styles.actionLink}>Find Roles →</span>
          </div>

          {/* For Admins Card */}
          <div className={`${styles.featureCard} ${styles.adminCard}`} onClick={() => navigate('/login')}>
            <div className={styles.cardIcon}>🛡️</div>
            <h3>For Administrators</h3>
            <p>Post open positions instantly, manage incoming student applications, and approve timesheets efficiently with our high-end ledger system.</p>
            <span className={styles.actionLink}>Access Dashboard →</span>
          </div>
        </div>
      </section>

      {/* 5. MASSIVE FOOTER */}
      <footer className={styles.footer}>
        <div className={styles.footerGrid}>
          <div className={`${styles.footerCol} ${styles.footerBrand}`}>
            <div className={styles.footerLogo}>
              <div className={styles.footerLogoOrb}>💼</div>
              <span className={styles.footerLogoText}>WorkStudy</span>
            </div>
            <p className={styles.footerDesc}> Empowering the next generation of professionals through streamlined campus employment and an ultra-premium experience.</p>
          </div>
          
          <div className={styles.footerCol}>
            <h4>Platform</h4>
            <div className={styles.footerLinks}>
              <span className={styles.footerLink} onClick={promptAuth}>Browse Jobs</span>
              <span className={styles.footerLink} onClick={promptAuth}>Departments</span>
              <span className={styles.footerLink}>Pricing</span>
              <span className={styles.footerLink}>About Us</span>
            </div>
          </div>

          <div className={styles.footerCol}>
            <h4>Resources</h4>
            <div className={styles.footerLinks}>
              <span className={styles.footerLink}>Help Center</span>
              <span className={styles.footerLink}>Employer Guide</span>
              <span className={styles.footerLink}>Student Guide</span>
              <span className={styles.footerLink}>System Status</span>
            </div>
          </div>

          <div className={styles.footerCol}>
            <h4>Legal</h4>
            <div className={styles.footerLinks}>
              <span className={styles.footerLink}>Privacy Policy</span>
              <span className={styles.footerLink}>Terms of Service</span>
              <span className={styles.footerLink}>Cookie Policy</span>
              <span className={styles.footerLink}>Security</span>
            </div>
          </div>
        </div>

        <div className={styles.footerBottom}>
          <p>© 2026 WorkStudy Platform. All rights reserved.</p>
          <div style={{display: 'flex', gap: '20px'}}>
            <span className={styles.footerLink}>Twitter</span>
            <span className={styles.footerLink}>LinkedIn</span>
            <span className={styles.footerLink}>GitHub</span>
          </div>
        </div>
      </footer>

      {/* Auth Prompt Modal (Maintains existing functionality) */}
      <Modal 
         open={isAuthModalVisible} 
         onCancel={() => setIsAuthModalVisible(false)} 
         footer={null}
         centered
         aria-labelledby="auth-modal-title"
      >
         <div style={{ textAlign: 'center', padding: '24px 0' }}>
            <div style={{ width: 64, height: 64, background: '#eff6ff', borderRadius: '50%', margin: '0 auto 16px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
               <LockOutlined style={{ fontSize: 24, color: '#ff3366' }} />
            </div>
            <Title id="auth-modal-title" level={3} style={{ marginBottom: 16 }}>Authentication Required</Title>
            <Paragraph style={{ color: '#6b7280', fontSize: 16, marginBottom: 32 }}>
               {searchTerm ? `Sign in to discover roles related to "${searchTerm}".` : 'Please sign in or create a student account to explore the database.'}
            </Paragraph>
            <Space size="middle" direction="vertical" style={{ width: '100%' }}>
               <Button type="primary" size="large" block onClick={() => navigate('/login')} style={{ height: 48, borderRadius: 8, background: '#ff3366', borderColor: '#ff3366' }}>
                  Login to WorkStudy
               </Button>
               <Button size="large" block onClick={() => navigate('/register')} style={{ height: 48, borderRadius: 8 }}>
                  Create an Account
               </Button>
            </Space>
         </div>
      </Modal>

    </div>
  );
}
